### ISSUE TITLE
Q: Minimum pin requirement for ESP32 (WiFiNINA)

### ISSUE THREAD

**Issue by dronecz** [joeycastillo/The-Open-Book#13]
Hello, 

could you please confirm me that this is all what I need to use WiFiNINA with your board:  

```
// Initialize the WiFi client library
#define SPIWIFI       SPI  // The SPI port
#define SPIWIFI_SS    13   // Chip select pin
#define ESP32_RESETN  12   // Reset pin
#define SPIWIFI_ACK   11   // a.k.a BUSY or READY pin
```
I found it with your [example](https://gist.github.com/joeycastillo/12273bd0befc297f20f61146fa9806f5) and I´m just wondering if this all what I need to use WiFi with your board? Also pins correspond to Feather Wing layout? 

Many thanks for your answer.

**Comment by joeycastillo** [comment]
Apologies, I thought I responded to this question and just noticed it had gone unanswered. 

Yes, this is the pinout for the Open Book, as well as the M4 Feather + eBook Wing. Some other Feathers swap the numbers around, but those three pins physically next to VBUS are the ones you need.
