### ISSUE TITLE
Use case: update conference room meetings remotely

### ISSUE THREAD

**Issue by sunk818** [joeycastillo/The-Open-Book#14]
I know a little out of your use case, but was thinking this would be cool to have as a conference room display to display an eBook or PDF to show meeting changes more frequently than paper. If there was remote SSH, FTP, and/or WiFi then I could update the file remotely?

Not expecting you to change any hardware design or make the price go up... just something for you to consider in the far future.

**Comment by joeycastillo** [comment]
Wifi has definitely been a nice-to-have from the start, but like you mentioned, keeping the price down has been the main prerogative. The good news is that both designs in this repository are compatible with the [Adafruit AirLift FeatherWing](https://www.adafruit.com/product/4264), which means you can plug that board onto the back (or in the case of the Wing, stack it on with stacking headers) to add wifi. 

I did [something similar for train schedules](https://twitter.com/josecastillo/status/1191197422866841600) with one of the prototypes, so the kind of use case you're describing is definitely within the realm of the possible :)
