### ISSUE TITLE
What is display PPI/DPI?

### ISSUE THREAD

**Issue by Symbian9** [joeycastillo/The-Open-Book#17]
Can you specify what is resolution of display and its PPI/DPI?

As I can see on photos its PPI is very low (bold pixels)

**Comment by joeycastillo** [comment]
The resolution is 400x300 at 120 dpi, which is low for displaying graphics, but workable for reading text. It's a tradeoff: higher-resolution screens are more expensive, and I'm trying to keep the BOM cost as low as possible. [This page](http://www.e-paper-display.com/products_detail/productId=321.html) has specifications for the panel if you're interested in learning more.

Thanks for the feedback!
