### ISSUE TITLE
Photo of board without e-ink display

### ISSUE THREAD

**Issue by sdas41395** [joeycastillo/The-Open-Book#25]
Hey Joey,

Amazing DIY project! Me and my girlfriend stumbled upon this recently while surfing the internet for a e book reader. We're not that versed in reading electrical schematics and were hoping you could also include a photo of the front without the e-ink display so we can match the connections to the drawn schematics to help understand how to do it. 

Thank you so much for this cool project and very excited to see how it goes forward!

Thanks,
Shoham

**Comment by DCelectronics** [comment]
Hi Shoham,
The following would help you and others to visualize the display connections and understand how to do it.

Quoting Joey here (from issue #32):
"First, make sure that the gray tabs are open. Then as far as fitting the connector, I've found it helps to kind of gently bend the cable in between the connector area and the ground pour before you thread it through the hole; that gives you some leverage to work it in, like so:"
![Connector](https://user-images.githubusercontent.com/1765152/88682142-56fde700-d0c0-11ea-8448-7691d53fc13a.gif)
And this short clip is from a twitter post by Joey:
![Screen_folding](https://user-images.githubusercontent.com/48794887/96347487-0fa84680-1070-11eb-8bcd-57b8ad4e79da.gif)
As the silkscreen states "... Secure the screen to this area with double sided tape; you don't need this documentation anymore."

The typical bending radius of a two layer flexible board (referring to the amber ribbon that comes out of the display) is about 12 times the thickness of the flexible board (which is about 4mils). 
Using a very high bonding double sided tape with a thickness of about 50mils (such as 3M Scotch 5952 or equivalent) should be fine to secure the display on the board.

I am thankful that Joey posted these short clips on the internet.
