### ISSUE TITLE
Please add beginner tutorial

### ISSUE THREAD

**Issue by ttpro1995** [joeycastillo/The-Open-Book#27]
Hi, I just found this repo on github. It is interesting to make my own e-reader. However, I would like to know if there are any How-to guide (detail step by step, preferable to someone new to do-it-yourself hardware stuff)  to make one my own e-reader.

**Comment by babarrett** [comment]
Hi, doing DIY projects is fun and educational. I highly recommend it.
I would, however, suggesting something smaller to start. There are many things to learn to make the e-reader. None to difficult, but taken together it will be time consuming.
For the electronics assembly part I'd suggest googling for "blinky PCB." Something like this kit is a reasonable place to start:  https://www.pcboard.ca/led-blinky-kit
It comes with all the needed parts. You'll still need solder ans a soldering iron to complete it. There are 100's of soldering instructional videos on-line to get you started.

Next you can get an SMD practice board from ebay or amazon and complete that too.
More to do after that too.
