### ISSUE TITLE
Drill files are not included in kitspace download

### ISSUE THREAD

**Issue by kasbah** [joeycastillo/The-Open-Book#37]
Hey, moving the Gerbers and drill files into separate folders isn't supported by Kitspace yet. Your pages currently won't update any more. 

Options are:
- Move the drill and gerber files into one folder and update the kitspace.yaml
- Wait till we add support for it: https://github.com/kitspace/kitspace/issues/12

**Comment by joeycastillo** [comment]
Weird, I updated the files but I thought the structure was the same (it's just the directory structure that Eagle outputs). If I just move everything to the root of the dated folder it should work though?

**Comment by kasbah** [comment]
You are right, it is the same as before and it's building fine now. Not sure what happened

What I said about the separate folders is true though and currently the gerber download zips are missing the .xln drill files.

**Comment by joeycastillo** [comment]
Hey sorry it took so long to resolve this; was a simple fix, but it came in a month of distractions. I think it should be good now.
