### ISSUE TITLE
Adafruit Compatible Stackable Header for the Feather to the FeatherWing Wifi is too thin and falls out of the eBook Wing's Header

### ISSUE THREAD

**Issue by lvw5264** [joeycastillo/The-Open-Book#40]
In the BOM, the Top feather header and Bottom Feather header are used to allow the Feather to stack solderlessly on top of the eBook Wing, breadboard style. I would have used the cheaper option of just cutting a Raspberry Pi header in half but I didn't want to risk that.

The feather comes with standard male break away header that is square so it fits snug in the breadboard style header on the eBook Wing. However, these would not allow the FeatherWing wifi to stack on top. Just like these:

https://www.adafruit.com/product/3002

So Adafruit provides a $1 thin pin stackable female header set commonly used in the Arduino for the header to connect to other boards, which is of course, able to stack to thin pin stackable female headers like itself just fine.

https://www.adafruit.com/product/2830

Unfortunately, these thin pin stackable female headers are too thin compared to the standard male break away header, and easily fall out of the breadboard style one on the eBook Wing, so I could not use them for the purpose of stacking the FeatherWing Wifi chip atop it. Observe the example shown in this product guide to witness the clear difference between the stackable female header Adafruit uses, vs one using square pins just like the standard male break away header:

https://www.rugged-circuits.com/components/8-pin-stacking-header

![](https://images.squarespace-cdn.com/content/v1/529a48e1e4b09eb80191621d/1386470427491-GREQY0SB2QEE217H9PFH/ke17ZwdGBToddI8pDm48kJl9udw_wGTj-jqa9OFlEHjlfiSMXz2YNBs8ylwAJx2qgRUppHe6ToX8uSOdETM-XldvY_sAIyUlfjhoEMtv77EejWM5qcEDMai0hprcAVmprsT9L6CduqmEFmNwwu0AjrxvuB1-1brgCNMG9dB-_8Q/sheaders2.gif?format=750w)

https://www.rugged-circuits.com/components/6-pin-stacking-header

(buying 2 of the 8 pin and 2 of the 6 pin female stacking header would solve this issue)

How did you stack the FeatherWing Wifi chip atop, and with what stackable female headers? Do I have to buy those square ones as above and not flat? it seems to be harder to find, and if so needs to be noted in the guide.

An alternative cheap option is to use longer square male header, and then solder the thin pin female stackable header (or a non stackable header if its the last in the stack) to the *bottom* of the FeatherWing instead of the top of the feather. Of course this means that the header is now in an unusual nonstandard reversed position, but at least Adafruit doesn't solder down the headers so it could work. Did you do that?

https://www.adafruit.com/product/400

**Comment by joeycastillo** [comment]
I used the same stacking Feather headers from Adafruit, product 2830, and I have not experienced an issue with the pins being that loose when paired with the headers in the BOM. Can you post a photo of the headers you are using? The ones I have here look like this, and they do fit securely and stay put even when inverted or shaken.

![image](https://user-images.githubusercontent.com/1765152/97807977-e1129a00-1c31-11eb-9490-fa68d2de1ee6.png)

![image](https://user-images.githubusercontent.com/1765152/97807988-ebcd2f00-1c31-11eb-863d-98f0c0376d53.png)

**Comment by lvw5264** [comment]
I made a video of how the thin pin female stackable header from Adafruit onto the white socket of the BOM just doesn't make a good electrical connection and easily falls out, but I tried to find somewhere convenient to upload it, but I couldn't find it. No clue how yours fits snugly.

I guess the answer is clear to me anyway, I have to use those thicker square female stackable headers as linked above. Do look into it, I'm sure there must be a female stackable header that is properly square on digikey to recommend for the wifi FeatherWIng instead.

**Comment by joeycastillo** [comment]
Thanks for the suggestion and I appreciate the report; will definitely search Digikey and see what I can find. Also plan to order some more stacking Feather headers from Adafruit to see if I can reproduce the issue.

**Comment by DCelectronics** [comment]
@lvw5264, If you used the BOM parts: Amphenol ICC / FCI 89898-312LF and 89898-316LF, they do not have the typical fork orientation and retention mechanism, and the budget Adafruit headers are too thin for these sockets (the male portion of the stackable Adafruit headers do not have square cross section area). 
The following pictures may help you visualize how the socket engages with the header pins.
![609-3046-ND](https://user-images.githubusercontent.com/48794887/98489619-d1c8b900-21fc-11eb-90c7-a67a47401e0d.jpg)
![Amphenol](https://user-images.githubusercontent.com/48794887/98489745-53b8e200-21fd-11eb-93ec-5de07172f83f.png)
![76357-301LF](https://user-images.githubusercontent.com/48794887/98490146-a1821a00-21fe-11eb-97b9-ae02eb77de50.jpg)
These two parts should adders the issue.
https://www.samtec.com/products/ssq-112-03-f-s
https://www.samtec.com/products/ssq-116-03-f-s
![IMG_1434](https://user-images.githubusercontent.com/48794887/98489039-4c440980-21fa-11eb-9037-381099ce05f1.JPG)
