### ISSUE TITLE
Wiki documentation link correction for OB BOM

### ISSUE THREAD

**Issue by cynorg** [joeycastillo/The-Open-Book#41]
The link to the kitspace BOM for the Open Book at https://github.com/joeycastillo/The-Open-Book/wiki/Open-Book-Documentation#bom-notes points to https://kitspace.org/boards/github.com/joeycastillo/the-open-book/ instead of https://kitspace.org/boards/github.com/joeycastillo/the-open-book/open-book/ - which results in the 29 component BOM for the eBook-Wing, rather than the 49 component BOM for the Open Book (this happens because https://kitspace.org/boards/github.com/joeycastillo/the-open-book/ redirects you to https://kitspace.org/boards/github.com/joeycastillo/the-open-book/ebook-wing/ )

Apparently wiki's aren't part of GitHub repos, so raising an issue seemed the best way to get this correction in front of you, with new boards up on the open book Tindie it seemed like folks might just blindly click and end up missing a bunch of stuff ;)

cheers.

**Comment by joeycastillo** [comment]
Thanks so much for pointing that out! Fixed now.
