### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by moje01konto** [joeycastillo/The-Open-Book#42]
Is possible put Ruby to this device?

**Comment by joeycastillo** [comment]
I am not sure about Ruby; the device does support Python in the form of [CircuitPython](https://circuitpython.org/board/openbook_m4/), as well as C++ in the form of Arduino. Adafruit has [an article about alternative programming languages for the SAMD51](https://learn.adafruit.com/alternative-languages-for-programming-SAMD-boards), the microcontroller in this board, but note that support for the peripherals like the screen and buttons only exist, for now, in C++ and Python.
