### ISSUE TITLE
E-Paper Display

### ISSUE THREAD

**Issue by markgibb02** [joeycastillo/The-Open-Book#49]
The BOM calls for the GDEW042T2 display from Good Display. As far as I can see, this has been sold out for months, with no sign of coming back in stock. Is there a direct replacement display which can be used without changing hardware and code?

**Comment by joeycastillo** [comment]
I hear you and totally feel your frustration. I’ve been in touch with the manufacturer and the fact is, they’re experiencing long lead times for the glass necessary to make the display. I don’t know if it’s pandemic related, but given how much it has turned the world upside down, I wouldn’t be surprised. The expectation is that they will be able to resume production around April. 

At this time there really isn’t another display that’s either mechanically or code compatible with this design, and moreover none that I’ve seen that can hit the same price point that would keep the project inexpensive and accessible. Given all that, my instinct is to just wait out this supply crunch and hope things get better as the year progresses.

**Comment by MixedMatched** [comment]
It looks like the display is [back in stock](https://buy-lcd.com/products/42inch-e-inkanel-spi-interface-buy-eaper-display).
