### ISSUE TITLE
Put the BOMs in the repository, as CSV

### ISSUE THREAD

**Issue by SamantazFox** [joeycastillo/The-Open-Book#51]
Please add the bills of materials, for the different variants, in this repository. Preferably as CSV, which is largely supported, and text only.

It is very important to keep the whole project together, to be futureproof (i.e not relying on an external provider like Kitspace, that may shut down, and would require to reverse engineer the schematics to get a BOM).

**Comment by aceat64** [comment]
They already are:
https://github.com/joeycastillo/The-Open-Book/blob/main/Open%20Book%20Feather/1-click-bom.csv
https://github.com/joeycastillo/The-Open-Book/blob/main/eBook%20Feather%20Wing/1-click-bom.csv

**Comment by SamantazFox** [comment]
@aceat64 AH! Thanks, lol
