### ISSUE TITLE
Dual Display Support

### ISSUE THREAD

**Issue by xambu** [joeycastillo/The-Open-Book#52]
E-Ink book readers have all been single display. Kind of makes sense because a button press can shift the page. But there is something comforting about two pages. I think a PCB (think two) that can be connected together with fewer components on one of the PCB's will be give this reader a very good unique selling point. The design can be made such that there is an additional ribbon cable (optional) that connects both the PCB's (which are the same as for a single PCB design). When the ribbon is in use, one of the boards with the CPU can handle both the displays. Additionally, the two screens when the books is closed protect each other. So the design change won't increase the cost of the PCB or BOM for the single display model while allowing for the dual display to be made. Seeing two pages can also be useful for students who are doing research and want to read two different thing at the same time. For example, problem and solution.

**Comment by gustavklopp** [comment]
The first step is to have a mono display already working (with note taking available). I think assembling the mono display is already quite a challenge.
