### ISSUE TITLE
I wanted to build one but when i try to order the components it is written that they are retired?

### ISSUE THREAD

**Issue by TrueGorOn** [joeycastillo/The-Open-Book#58]
I am in need of an ebook reader. I don't want to buy a kindle or that sort. This project is really interesting. So wanted to give it a go. But when i visited the site that are linked here, for the components, it is written that they are retired. I am very sad to see the end of this project. Hoping someday it will come back. So any idea when the board and other components will be available for purchase?

**Comment by joeycastillo** [comment]
I'm working on a new board based around the Raspberry Pi Pico even as we speak. it's been a challenging couple of years for making things; the world of early 2020, when you could dream up a design and have the chips within a week, feels far away now, and a project with a BOM the size of the original Open Book's seems a lavish indulgence. 

the Pi Pico book will be much simpler and take rechargeable AAA batteries, so it may not be as svelte as the original. but in using the Pi Pico, it gets the BOM down to just over a dozen parts, all widely available. I've been [refining the design](https://twitter.com/josecastillo/status/1549123078411751425) and I hope to have it published later this summer, with at least a few kits available before the year is out. With it will come a complete overhaul of the firmware, which frankly will require some community support to get it over the finish line. 

It's more of a project reset: same goals, same form factor and many of the same parts, but starting fresh and incorporating all of the lessons learned over the last two years and change. Once I get there, I plan to archive the old repo in a branch and close all the old issues with an message making clear the new direction; if you remain subscribed to this issue, you'll hear about it as soon as we're ready to make moves.
