### ISSUE TITLE
Dead link for Open Book Board Manager

### ISSUE THREAD

**Issue by rlorenr** [joeycastillo/The-Open-Book#61]
The [oddlyspecific link](https://www.oddlyspecific.org/boardsupport/package_oddlyspecific_index.json) that  is specified in the [Documentation](https://github.com/joeycastillo/The-Open-Book/wiki/Open-Book-Documentation) just takes me to the oddlyspecific landing page, and I can't find any json files anywhere on that site, so I'm guessing you took it down. Could you upload that json file to this repo for posterity's (and my) sake?

**Comment by joeycastillo** [comment]
Apologies, I moved to a new domain name and set up the redirect not realizing that it would break the link to the board support package. 

I've updated the link in the wiki; here is the new board support URL: https://www.oddlyspecificobjects.com/boardsupport/package_oddlyspecific_index.json

The Arduino core featuring the Open Book board definition is [here](https://github.com/joeycastillo/ArduinoCore-samd), but there are also some other utilities and such that ride alongside it and may be tough to find in the repo. This ZIP file contains the full contents of the boardsupport directory: [boardsupport.zip](https://github.com/joeycastillo/The-Open-Book/files/9806543/boardsupport.zip). (note that it also includes a separate JSON file for SAM D11 board support, which is not required for the Open Book)
