### ISSUE TITLE
Screen daughter board

### ISSUE THREAD

**Issue by nicolasknight** [joeycastillo/The-Open-Book#65]
I'm going through the BOM and making sure I have every part ready to order first.
The screen shot from hackaday shows a daughter board the screen plugs into to the right of the pico.
The link to buy the screen shows no board and the video for the build was on twitter so it's no longer available.

Any chance I can get confirmation the board is included with the screen?

Also, can the video be reuploaded?

**Comment by joeycastillo** [comment]
So the board isn’t something that comes with the display. It’s a custom module I designed that you can pick up from the Oddly Specifc Objects shop: https://shop.oddlyspecificobjects.com/products/open-book-castellated-e-paper-module

And the video, wow, I thought it was included in my Twitter archive but I’m seeing now that it’s not, so I’ll need to download it and preserve it before it’s deleted forever. For now it seems to still be live here: https://twitter.com/i/broadcasts/1OyKAVPjrvaGb
