### ISSUE TITLE
Links on reboot Readme point to deleted Twitter account

### ISSUE THREAD

**Issue by ryanayoung** [joeycastillo/The-Open-Book#66]
Just wanted to point out that two of the links in the Readme on the reboot branch point to your now defunct(and rightly so) twitter account.

The one that mentions the only location for the ascii codes is in a twitter post, as well as the 30 minute build video link are no longer valid since you moved to mastodon.

**Comment by darigovresearch** [comment]
@ryanayoung thanks for raising this

For reference below are the items mentioned
The Branch - https://github.com/joeycastillo/The-Open-Book/tree/reboot
Link to the ASCI thread - https://twitter.com/josecastillo/status/1533103137455751168
Link to the video - https://twitter.com/josecastillo/status/1571337869998067713

Is there any interim reference anyone knows that can be used?
