### ISSUE TITLE
Migrate to KiCad for PCB design?

### ISSUE THREAD

**Issue by foozmeat** [joeycastillo/The-Open-Book#9]
Hi, great project idea and I'm excited to contribute. However, I'm not excited to use Eagle. KiCad is mature enough to handle this project and is FOSS. Would you consider moving to it?

**Comment by joeycastillo** [comment]
I would be thrilled to move to KiCad! I know that it being in Eagle is a barrier to people who want to contribute, but don't want to or can't pay for a monthly subscription. For now though, Eagle is the tool that I know and that I can use to iterate quickly. Once I get the design stable, I'd love to learn KiCad and remake the project there, but it might be something that happens later, once I've got a revision of the board finalized.

**Comment by keen101** [comment]
I don't use kicad, as I also learned and use Eagle, but i believe kicad has a tool to import and migrate eaglecad designs to some degree. Not sure how well it works,  but might help save some time recreating from scratch. 

https://kicad-pcb.org/blog/2017/10/Testing-Eagle-import-plugins/

**Comment by LogoiLab** [comment]
It is sort of a waste to have this be open source if it requires fairly expensive software to contribute to/utilize. KiCad isn't that bad. I use it all the time, definitely usable, you dont get all those crazy macros and such that youd get with something like Altium, but it works well.

**Comment by jupart** [comment]
I could help with the migration. I use KiCad at work designing/changing 20-30 PCBs a year.
